-- ============================================================================
-- 038_pickleball_settings.sql
-- Finishes the pickleball rollout — must run AFTER 037 has been committed
-- (55P04: an enum value can't be used in the same transaction that added it).
--
--   1. Enrol pickleball in the per-sport approval-flow toggle (mig 018).
--   2. Add per-sport scoring config columns on `matches`
--      (best-of and target points). Defaults mirror the badminton choices —
--      best of 3 sets, target 21 points — per product decision.
--   3. Refresh the `tournaments.sport` CHECK constraint so the four
--      originally-listed sports plus foosball (missed when foosball shipped)
--      and pickleball are all allowed.
--
-- Idempotent: every statement is guarded by IF NOT EXISTS / ON CONFLICT,
-- and the CHECK constraint is dropped only if its prior name exists.
-- ============================================================================

-- 1. Approval-flow enrolment
INSERT INTO public.sport_settings (sport, approval_enabled)
VALUES ('pickleball', true)
ON CONFLICT (sport) DO NOTHING;

-- 2. Per-sport scoring config on matches
ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS pickleball_sets          INT DEFAULT 3;
ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS pickleball_target_points INT DEFAULT 21;

-- 3. Tournaments allowed-sports list
--    Drop the old CHECK (which omitted foosball + pickleball) and replace
--    with the full set. The constraint name was auto-generated by Postgres
--    when the table was created in 020 — `tournaments_sport_check` matches
--    the default naming convention.
ALTER TABLE public.tournaments
  DROP CONSTRAINT IF EXISTS tournaments_sport_check;
ALTER TABLE public.tournaments
  ADD CONSTRAINT tournaments_sport_check
  CHECK (sport IN (
    'cricket', 'football', 'badminton', 'table_tennis', 'foosball', 'pickleball'
  ));
